export { dateLib, type TdateLib } from "./dateLib"
export { makeDayLink } from "./makeDayLink"
export { timeDiffSplitted } from "./timeDiffSplitted"
export { getTrackElapsedTime } from "./getTrackElapsedTime"
export { time2359, getMaxElapsedTime } from "./getMaxElapsedTime"
